get:
  security: []
  tags: []
  description: |
    Retrieve the Openapi  documentation for the API.
  operationId: docs_openapi_get
  parameters: []
  responses:
    '200':
      description: |
        OK.
