# Generated by Django 2.1.2 on 2019-03-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('youtube_id', models.CharField(max_length=32, unique=True)),
                ('last_downloaded', models.DateTimeField(default=None, null=True)),
                ('download_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'video',
            },
        ),
    ]
